version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: subscription_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-subscription_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U subscription_user -d subscription_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://subscription_user:${DB_PASSWORD:-subscription_password}@postgres:5432/subscription_db
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:





